language: cpp
dist: xenial

addons:
  apt:
    packages:
    - qtbase5-dev
    - qttools5-dev-tools
    - libqt5opengl5-dev
    - libusb-1.0-0-dev
    - libfftw3-dev
    - binutils-dev
    - rpm

matrix:
  include:
    - compiler: gcc
      env: CMAKE_CXX_COMPILER=g++-5
      os: linux
    - compiler: clang
      env: CMAKE_CXX_COMPILER=/usr/bin/clang++
      os: osx

before_install:
    - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then
          brew update; brew install qt5 fftw binutils ;
          export CMAKE_PREFIX_PATH=$(brew --prefix qt5);
          echo "CMAKE_PREFIX_PATH=${CMAKE_PREFIX_PATH}" ;
      fi
    - if [[ "$TRAVIS_OS_NAME" != "osx" ]]; then pip install cmake --user; fi

before_script:
    - mkdir build
    - cd build
    - cmake -DCMAKE_CXX_COMPILER=${CMAKE_CXX_COMPILER} -DCMAKE_PREFIX_PATH=${CMAKE_PREFIX_PATH} ../

script:
    - make -j4 # create either a bin or a bundle (.app) - depending on openhantek/CMakeLists.txt
    - sudo make -j4 package # simply pack the binary, otherwise populate the bundle below
    - if test -d openhantek/OpenHantek.app; then
          export PATH=${CMAKE_PREFIX_PATH}/bin:${PATH} ;
          cd openhantek ;
          macdeployqt OpenHantek.app -always-overwrite -verbose=2 ;
          python ../../utils/macdeployqtfix/macdeployqtfix.py OpenHantek.app/Contents/MacOS/OpenHantek ${CMAKE_PREFIX_PATH} ;
          macdeployqt OpenHantek.app -dmg -no-plugins -verbose=2 ;
          ls -lhAFRO@ OpenHantek.* ;
          xattr -l OpenHantek.dmg ;
          cd .. ;
      else
          ls -l packages ;
          true;
      fi
    - ls -l openhantek || true

before_deploy:
    - if test -d openhantek/OpenHantek.app; then
          cd openhantek ;
          sudo tar -cvzf ../packages/openhantek_*_osx_*.tar.gz OpenHantek.app ;
          if test -f OpenHantek.dmg ; then
            sudo mv OpenHantek.dmg ../packages/$(basename ../packages/openhantek_*_osx_*.tar.gz .tar.gz).dmg ;
          fi ;
          cd .. ;
      else
          true;
      fi
    - ls -l packages || true

deploy:
  provider: releases
  api_key: $GITHUB_TOKEN
  file_glob: true
  file: packages/*
  skip_cleanup: true
  on:
    tags: true
