language: cpp
dist: xenial

addons:
  apt:
    packages:
    - qtbase5-dev
    - qttools5-dev-tools
    - libqt5opengl5-dev
    - libusb-1.0-0-dev
    - libfftw3-dev
    - binutils-dev
    - rpm

matrix:
  include:
    - compiler: gcc
      env: CMAKE_CXX_COMPILER=g++-5
      os: linux
    - compiler: clang
      env: CMAKE_CXX_COMPILER=/usr/bin/clang++
      os: osx

before_install:
    - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew update; brew install qt5 fftw binutils dylibbundler; export CMAKE_PREFIX_PATH=$(brew --prefix qt5); fi
    - if [[ "$TRAVIS_OS_NAME" != "osx" ]]; then pip install cmake --user; fi

before_script:
    - mkdir build
    - cd build
    - cmake -DCMAKE_CXX_COMPILER=$CMAKE_CXX_COMPILER -DCMAKE_PREFIX_PATH=$CMAKE_PREFIX_PATH ../

script:
    - make -j4
    - ls -l openhantek || true
    - sudo make -j4 package # these bottom lines go to section before_deploy: after test
    - if test -d openhantek/OpenHantek.app; then
          cd openhantek
          && /usr/local/opt/qt5/bin/macdeployqt OpenHantek.app -always-overwrite -verbose=2
          && curl -o /tmp/macdeployqtfix.py https://raw.githubusercontent.com/arl/macdeployqtfix/master/macdeployqtfix.py
          && python /tmp/macdeployqtfix.py OpenHantek.app/Contents/MacOS/OpenHantek /usr/local/opt/qt5
          && sudo tar -cvzf ../packages/openhantek_*_osx_*.tar.gz OpenHantek.app
          && /usr/local/opt/qt5/bin/macdeployqt OpenHantek.app -dmg -no-plugins -verbose=2
          && mv OpenHantek.dmg ../packages/$(basename ../packages/openhantek_*_osx_*.tar.gz .tar.gz).dmg
          && cd ..
          && ls -la packages
      else 
          true ; # success anyway
      fi

before_deploy:
    - ls -l packages || true

deploy:
  provider: releases
  api_key: $GITHUB_TOKEN
  file_glob: true
  file: packages/*
  skip_cleanup: true
  on:
    tags: true
