language: cpp
dist: xenial

addons:
  apt:
    packages:
    - qtbase5-dev
    - qttools5-dev-tools
    - libqt5opengl5-dev
    - libusb-1.0-0-dev
    - libfftw3-dev
    - binutils-dev
    - rpm

matrix:
  include:
    - compiler: gcc
      env: CMAKE_CXX_COMPILER=g++-5
      os: linux
    - compiler: clang
      env: CMAKE_CXX_COMPILER=/usr/bin/clang++
      os: osx

before_install:
    - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew update; brew install qt5 fftw binutils; export CMAKE_PREFIX_PATH=$(brew --prefix qt5); fi
    - if [[ "$TRAVIS_OS_NAME" != "osx" ]]; then pip install cmake --user; fi

before_script:
    - mkdir build
    - cd build
    - cmake -DCMAKE_CXX_COMPILER=$CMAKE_CXX_COMPILER -DCMAKE_PREFIX_PATH=$CMAKE_PREFIX_PATH ../

script:
    - make -j4
    - sudo make -j4 package # TEST: build without release
    - ls -la . openhantek # TEST:
    - test -d packages && ls -laR packages # TEST: depends on make package
    - test -d OpenHantek.app && ls -laR OpenHantek.app # TEST: macosx specific

before_deploy:
    - sudo make -j4 package

deploy:
  provider: releases
  api_key: $GITHUB_TOKEN
  file_glob: true
  file: packages/*
  skip_cleanup: true
  on:
    tags: true
